### ISSUE TITLE
Trouble Compiling with MKL

### ISSUE THREAD

**Issue by Shackman287** [acuoci/edcSMOKE#1]
I can compile the minimilast version with no problem. I get warning that "could not open file ...", but I assume they are not used so it's okay (Shouldn't these be recognized since they are in openSMOKEpp4edcSMOKE).

When I try compiling with -DOPENSMOKE_USE_MKL=1 (and setting the MKL paths), it starts compiling and  crashes saying it can't find fvCFD.H (The main OF header). It's like including the MKL paths has made the compiler lose the OpenFOAM path. Have you experienced these problems before? Is this related to the warning of could not open file at the beginning of the compilation.

Thank you and great code! OF needed a real FR solver. Don't use reactingFoam, the reaction rates are cell size dependent!!! 
ShackMan

**Comment by Shackman287** [comment]
I fixed it. Acuoci, please add the following line in your options file
"-I$(FOAM_SRC)/OpenFOAM/lnInclude \

Then it compiles, with mkl :) Still not sure why MKL triggered the problem.

**Comment by GontzalLopez** [comment]
Hi Alberto, Im trying to compile edcSMOKE with the mybashrc.minimalist version in Openfoam v6 but the attatched errors appear when compiling the first edcSimpleSMOKE solver. 

I hope you can help me

Regards
![Capture](https://user-images.githubusercontent.com/61630172/98237493-4255a880-1f65-11eb-9838-10d6ff809630.JPG)

**Comment by santelima** [comment]
Hi
I can't compile the minimalist version. And I get the following error in the image. How can I fix this? 

Sincerely
![Uploading Capture du 2022-01-19 20-56-30.png…]()
